name: Create Package

on: 
  pull_request:
  push:

jobs:
  build:
    name: Create Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        #run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
        #run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
        run: echo ::set-output name=version::${GITHUB_REF#refs/*/}

      - name: Make zip file
        run: |
          mkdir build -p
          sed -i 's/cpc.version = "0.0.0"/cpc.version = "${{ steps.get_version.outputs.version }}"/g' cpc.xml
          zip --junk-paths build/cpc.mpackage README.md cpc.xml LICENSE config.lua
      
      - name: Store artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cmp.mpackage
          path: build/cpc.mpackage